### ISSUE TITLE
[Question] Does this case include clearance for the microcontroller?

### ISSUE THREAD

**Issue by JamesYeoman** [Pastitas/Redox-neodox-Case#3]
I want to be able to use standard microcontroller standoffs, and the falbatech case has enough clearance for that, but no model for 3d printing the design. Does this case have enough clearance? Or do I need to keep looking?

**Comment by Pastitas** [comment]
I don't think so, this design was done so that minimum height could be achieved, so it uses the sockets

**Comment by JamesYeoman** [comment]
Ok, thanks for the response
