### ISSUE TITLE
Labeling of tolerances on test

### ISSUE THREAD

**Issue by evidenz** [Pastitas/Redox-neodox-Case#6]
Perhaps I do not get it but how is the tolerance defined for the test? 

There are circles that increase in number (from top to bottom it is 1,2,3 and 4). Does that mean that the 4 circles indicate that it is the biggest tolerance of 0.20 mm? Or is it the other way around? From testing it actually feels the other way around (with the 4 circles my switches have the snuggest fitting?

Cheers and thanks for the help!

**Comment by Pastitas** [comment]
Yes, I notice now that it's kind of counterintuitive, I've adjusted the instructions in the readme. But yeah, you're right, the higher, the tighter the tolerance

**Comment by Pastitas** [comment]
Fixed 7ecffc8
